.TH SLICK-GREETER-CHECK_HIDPI 1 "April 6, 2017"
.SH NAME
slick-greeter-check-hidpi \- distro agnostic LightDM greeter
.SH SYNOPSIS
.B slick-greeter-check-hidpi
[
.I OPTIONS
]
.SH DESCRIPTION
.B Slick Greeter Check HiDPI
simple check to see if the current resolution is less that 1500px
in height (returns 1) or returns 2 if the resolution is considered
as HiDPI.
.PP
.SH OPTIONS
